apiVersion: v1
kind: Service
metadata:
  name: cicada-keycloak
spec:
  selector:
    app: cicada-keycloak
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 7796
      targetPort: 7796
      name: web-port

---

apiVersion: v1
kind: Service
metadata:
  name: cicada-ldap
spec:
  selector:
    app: cicada-ldap
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 7789
      targetPort: 7789

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicada-ldap
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cicada-ldap
    spec:
      containers:
        - name: cicada-ldap
          imagePullPolicy: IfNotPresent
          image: jian659/cicada-ldap
          ports:
            - containerPort: 7789
  selector:
    matchLabels:
      app: cicada-ldap

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicada-keycloak
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cicada-keycloak
    spec:
      containers:
        - name: cicada-keycloak
          imagePullPolicy: IfNotPresent
          image: jian659/cicada-keycloak
          ports:
            - containerPort: 7796
              name: web-port
          envFrom:
            - configMapRef:
                name: cicada-config
          env:
            - name: LDAP_USER_DN
              value: "${LDAP_USER_SEARCH_BASE}"
            - name: LDAP_BASE_DN
              value: "${LDAP_MANAGER_DN}"
            - name: LDAP_BASE_DN_PASSWORD
              value: "${LDAP_MANAGER_PASSWORD}"
            - name: LDAP_HOST
              value: "${LDAP_HOST}"
            - name: LDAP_PORT
              value: "${LDAP_PORT}"
            - name: CICADA_API_HOST
              value: "$(API_HOST)"
            - name: CICADA_API_PORT
              value: "$(API_PORT)"
            - name: JAVA_OPTS
              value: "$(KEYCLOAK_JAVA_OPTS)"
            - name: GC_LOG
              value: "$(KEYCLOAK_GC_LOG)"
            - name: PRESERVE_JAVA_OPTS
              value: "false"
  selector:
    matchLabels:
      app: cicada-keycloak

