apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicada-mongodb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cicada-mongodb
    spec:
      containers:
        - name: cicada-mongodb
          imagePullPolicy: IfNotPresent
          image: jian659/mongo
          resources:
           limits:
            memory: 100Mi
          ports:
            - containerPort: 27017
          envFrom:
            - configMapRef:
                name: cicada-config
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "$(MONGO_USER)"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "$(MONGO_PASSWORD)"
            - name: MONGO_INITDB_DATABASE
              value: "$(MONGO_DB)"
            - name: MONGO_PORT
              value: "$(MONGO_PORT)"
  selector:
    matchLabels:
      app: cicada-mongodb

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicada-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cicada-api
    spec:
      containers:
        - name: cicada-api
          imagePullPolicy: IfNotPresent
          image: jian659/cicada-api
          resources:
           limits:
            memory: 100Mi
          securityContext:
            capabilities:
              add:
              - SYS_ADMIN
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: cicada-config
          env:
            - name: BIND
              value: "0.0.0.0:8000"
            - name: MAX_WORKERS
              value: "1"
            - name: TIMEOUT
              value: "86400"
            - name: ACCESS_LOG
              value: "/app/gunicorn_access.log"
            - name: ERROR_LOG
              value: "/app/gunicorn_error.log"
            - name: KEYCLOAK_HOST
              value: "$(KEYCLOAK_HOST)"
            - name: KEYCLOAK_PORT
              value: "$(KEYCLOAK_PORT)"
            - name: LDAP_HOST
              value: "$(LDAP_HOST)"
            - name: LDAP_PORT
              value: "$(LDAP_PORT)"
            - name: MONGO_HOST
              value: "$(MONGO_HOST)"
            - name: MONGO_PORT
              value: "$(MONGO_PORT)"
            - name: NIFI_HOST
              # value: "$(NIFI_HOST)"
              value: "cicada-nifi-service"
            - name: NIFI_PORT
              # value: "$(NIFI_PORT)"
              value: "7795"
            - name: NIFI_MAX_TIMER_DRIVENTHREADCOUNT
              value: "$(NIFI_MAX_TIMER_DRIVENTHREADCOUNT)"
            - name: NIFI_MAX_EVENT_DRIVENTHREADCOUNT
              value: "$(NIFI_MAX_EVENT_DRIVENTHREADCOUNT)"
            - name: PRE_START_PATH
              value: "/app/deployment/prestart.sh"
            - name: NFS_HOST
              value: "$(NFS_HOST)"
            - name: API_SHARE_FOLDER
              value: "$(API_SHARE_FOLDER)"
  selector:
    matchLabels:
      app: cicada-api

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicada-web
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cicada-web
    spec:
      containers:
        - name: cicada-web
          imagePullPolicy: IfNotPresent
          image: jian659/cicada-web
          resources:
           limits:
            memory: 100Mi
          ports:
            - containerPort: 8000
  selector:
    matchLabels:
      app: cicada-web
